### ISSUE TITLE
Expose time zone for triggers via attribute

### ISSUE THREAD

**Issue by nzbart** [fudiwei/Quartz.Plugins.Attributes#1]
Thanks for this really handy utility - I've been using it for years.

Would it be possible to expose the trigger time zone via an optional property on the attribute? 

It appears to be hard-coded here:

https://github.com/fudiwei/Quartz.Extensions.JobAttribute/blob/5270bb6e57409e3efd63abd7cc570e90c08e5588/src/Quartz.Extensions.JobAttribute/Extensions/ServiceCollectionQuartzJobsExtensions.cs#L72

**Comment by fudiwei** [comment]
Sounds good.

I'll try it later.

**Comment by fudiwei** [comment]
You can do it now! 😄 

```csharp
// default is `TimeZoneInfo.Local`
[QuartzJob(CronExpression = "0 0 0 1 * ? ")]
public class MyJob : IJob {}

// use `TimeZoneInfo.Utc`
[QuartzJob(CronExpression = "0 0 0 1 * ? ", CronTimeZone = "UTC")]
public class MyJob : IJob {}

// use `Asia/Shanghai` timezone
[QuartzJob(CronExpression = "0 0 0 1 * ? ", CronTimeZone = "Asia/Shanghai")]
public class MyJob : IJob {}
```

**Comment by nzbart** [comment]
Thanks! I've upgraded and added time zones.
